<?php
use Drupal\Core\Routing\RouteMatchInterface;

/**
 *Implement  hook help().
*/

function react_integration_help($route_name, $route_match){

      switch($route_name) {
         case'help.page.react_integration':
           return '<p>'. t('This module integrates React with Drupal 10').'</p>;

       }

}
/**
 * Implements hook_page_attachements().
*/
function react_integration_page_attachements(array &attachments) {
 $attachements['#attached']['library'][] = 'react_integration/react';
}
