<?php

/**
 * @file
 * Implements the Augmentor NLP Cloud module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function augmentor_nlpcloud_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.augmentor_nlpcloud':
      $output = '<h3>' . t('Augmentor NLP Cloud') . '</h3>';
      $output .= '<p>' . t('Provides integration of Augmentor with the NLP Cloud API.') . '</p>';
      return $output;
  }
}
