<?php

/**
 * @file
 * Implements the Augmentor AWS module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function augmentor_aws_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.augmentor':
      $output = '';
      $output .= '<h3>' . t('Augmentor AWS AI') . '</h3>';
      $output .= '<p>' . t('Integration with AWS AI Services.') . '</p>';
      return $output;
  }
}
