name: Deploy Drupal to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql, gd
          coverage: none

      - name: Set up Composer
        uses: php-actions/composer@v6
        with:
          version: latest

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set GCP project
        run: gcloud config set project ${{ secrets.GCP_PROJECT }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT }}/alter-ai-agent
          docker build \
            --cache-from=$IMAGE_NAME:latest \
            -t $IMAGE_NAME:$GITHUB_SHA \
            -t $IMAGE_NAME:latest \
            .

      - name: Push Docker image
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT }}/alter-ai-agent
          docker push $IMAGE_NAME:$GITHUB_SHA
          docker push $IMAGE_NAME:latest

      - name: Deploy to Cloud Run
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT }}/alter-ai-agent
          gcloud run deploy alter-ai-agent \
            --image $IMAGE_NAME:$GITHUB_SHA \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
