name: Deploy to Google Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate with Google Cloud using Service Account JSON
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configure Docker to use gcloud as a credential helper
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev -q

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build Docker image and push to Artifact Registry
      - name: Build and Push Docker image
        run: |
          IMAGE="us-central1-docker.pkg.dev/alter-consult-464302/alterconsult-repo/alterconsult:${{ github.sha }}"
          docker build -t $IMAGE .
          docker push $IMAGE

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE="us-central1-docker.pkg.dev/alter-consult-464302/alterconsult-repo/alterconsult:${{ github.sha }}"
          gcloud run deploy alterconsult \
            --image $IMAGE \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --project alter-consult-464302
