name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger deployment on main branch push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3️⃣ Set project and configure gcloud
      - name: Set up gcloud project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud auth configure-docker gcr.io --quiet

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/alterconsult:$GITHUB_SHA .

      # 5️⃣ Push Docker image to GCR
      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/alterconsult:$GITHUB_SHA

      # 6️⃣ Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy alterconsult \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/alterconsult:$GITHUB_SHA \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --quiet
