name: 🚀 Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
      - master

env:
  PROJECT_ID: alter-consult-464302
  REGION: us-central1
  SERVICE: alterconsult
  REPO: alterconsult-repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ------------------------------------------------------
      # 1. Checkout code
      # ------------------------------------------------------
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      # ------------------------------------------------------
      # 2. Decode and configu
